---
run:
  concurrency: 6
  deadline: 5m
  skip-dirs-use-default: true
  skip-dirs:
    - contrib
    - dependencies
    - test
    - pkg/varlink
    - pkg/varlinkapi
  skip-files:
    - iopodman.go
    - swagger.go
linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - golint
    - gosec
    - lll
    - maligned
    - misspell
    - prealloc
    - unparam
    - nakedret
linters-settings:
  errcheck:
    check-blank: false
    ignore: encoding/json:^Unmarshal,fmt:.*
